### ISSUE TITLE
Review of interfaces

### ISSUE THREAD

**Issue by BMorinDrifter** [BMorinDrifter/metrics-cloudwatch-embedded#9]
Some folks with more Rust experience than me should give feedback on the interfaces, so I can dial down the volume of the disclaimers in the README.md.

Particularly concerned about `set_property<'a>(&'a self, name: impl Into<SharedString>, value: impl Into<Value>) -> &'a Self`

**Comment by aesterline** [comment]
Hi. 👋 I wouldn't say I'm an expert, but I could take a look and give feedback. I have been writing Rust full-time for about 18 months.

At first glance, I think I would change your function definition to:

`set_property(&self, name: impl Into<SharedString>, value: impl Into<Value>) -> &Self`

Or maybe... 

`set_property<V: Serialize>(&self, name: impl Into<SharedString>, value: V) -> &Self`

I need to see the full interface to see if `Serialize` makes sense.

What is the best way to give feedback? Open a PR with suggested changes?

**Comment by BMorinDrifter** [comment]
Thanks for the input @aesterline !

Comments here are fine, rather someone not put in a bunch of hours in a direction, submit a PR then have to tell them No.

That particular API relates to https://github.com/BMorinDrifter/metrics-cloudwatch-embedded/issues/10 as I'm still unsure what set of values will still get picked up by Cloudwatch.  I'm pretty sure there is a overall document size limit, if nothing else.

My concern with `set_property<V: Serialize>(&self, name: impl Into<SharedString>, value: V) -> &Self` is the value needs to be stored then serialized into every metrics document.  I can `Into<json::Value>`, not sure how I would store a `V: Serialize`.  Is there a way to have a struct passed into `serde` contain a json snippet that was serialized on set?

The rest of the interface is mostly handled by the `metrics` façade, so I'm inclined to pull the bold text about the interface not being stable next release as once I settle on what to do with `set_property` I don't think this crate is any less stable than many of the others I regularly use.
